spring.application.name=inventra

# Server Configuration
server.port=${PORT:8080}

# Database Configuration
spring.datasource.url=jdbc:mysql://ballast.proxy.rlwy.net:24755/railway?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=UAekWnGprXyYHwoDzqiUXUzeHqHhGyWu
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=DAXAJHbnX5omf9w3ovCkCUGE5ogipH+l5K0MNe3gCZg=
jwt.expiration=86400000

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=roboniumblade@gmail.com
spring.mail.password=afft gfbq telk ectn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Frontend URL
app.frontend.url=https://infosys-inventra.vercel.app/

# Logging
logging.level.com.infosys.inventra=DEBUG